In [1]:
import tensorflow as tf
tf.set_random_seed(777)

x_data = [[73,80,75],
         [93,88,93],
         [89,91,90],
         [96,91,100],
          [73,66,70]]
y_data = [[152],[185],[180],[196],[142]]

X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape = [None,1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]),name = 'bias')

hypothesis = tf.matmul(X,W) + b

cost = tf.reduce_mean(tf.square(hypothesis-Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [3]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(40001):
    cost_val,hy_val,_ = sess.run(
    [cost,hypothesis, train],feed_dict={X:x_data,Y:y_data})
    
    if step % 10 == 0:
        print(step,"Cost: ",cost_val,"\nPrediction:\n",hy_val)

0 Cost:  22990.527 
Prediction:
 [[22.048063]
 [21.619787]
 [24.096693]
 [17.54273 ]
 [18.633902]]
10 Cost:  22.684475 
Prediction:
 [[156.82468]
 [183.73058]
 [183.76433]
 [187.38177]
 [142.29912]]
20 Cost:  22.3325 
Prediction:
 [[157.25389]
 [184.27647]
 [184.2863 ]
 [187.95967]
 [142.7186 ]]
30 Cost:  22.23565 
Prediction:
 [[157.23598]
 [184.28455]
 [184.27858]
 [187.9741 ]
 [142.7278 ]]
40 Cost:  22.139427 
Prediction:
 [[157.21667]
 [184.29085]
 [184.26915]
 [187.98665]
 [142.7356 ]]
50 Cost:  22.043747 
Prediction:
 [[157.19742]
 [184.2971 ]
 [184.25975]
 [187.99916]
 [142.74338]]
60 Cost:  21.948666 
Prediction:
 [[157.1782 ]
 [184.30333]
 [184.25037]
 [188.01161]
 [142.75113]]
70 Cost:  21.854109 
Prediction:
 [[157.15906]
 [184.30954]
 [184.241  ]
 [188.02403]
 [142.75883]]
80 Cost:  21.76018 
Prediction:
 [[157.14   ]
 [184.31573]
 [184.23169]
 [188.03644]
 [142.76653]]
90 Cost:  21.666706 
Prediction:
 [[157.12099]
 [184.32191]
 [184.22238]
 [188.04881]
 [142.77417]]
100 C

1040 Cost:  14.891808 
Prediction:
 [[155.56738]
 [184.82175]
 [183.45929]
 [189.08347]
 [143.37692]]
1050 Cost:  14.838559 
Prediction:
 [[155.55344]
 [184.82619]
 [183.45241]
 [189.09302]
 [143.38208]]
1060 Cost:  14.785576 
Prediction:
 [[155.53954]
 [184.83061]
 [183.44553]
 [189.10255]
 [143.38725]]
1070 Cost:  14.732862 
Prediction:
 [[155.52567]
 [184.835  ]
 [183.43866]
 [189.11206]
 [143.39236]]
1080 Cost:  14.680499 
Prediction:
 [[155.51184]
 [184.8394 ]
 [183.43184]
 [189.12154]
 [143.39746]]
1090 Cost:  14.628456 
Prediction:
 [[155.4981 ]
 [184.8438 ]
 [183.42503]
 [189.131  ]
 [143.40256]]
1100 Cost:  14.576558 
Prediction:
 [[155.48433]
 [184.84814]
 [183.41823]
 [189.14044]
 [143.40761]]
1110 Cost:  14.525095 
Prediction:
 [[155.47064]
 [184.85248]
 [183.41147]
 [189.14984]
 [143.41264]]
1120 Cost:  14.473923 
Prediction:
 [[155.45702]
 [184.85683]
 [183.40472]
 [189.15923]
 [143.41768]]
1130 Cost:  14.42301 
Prediction:
 [[155.44342]
 [184.86113]
 [183.398  ]
 [189.16

2000 Cost:  10.922371 
Prediction:
 [[154.4137 ]
 [185.18446]
 [182.88545]
 [189.89693]
 [143.78285]]
2010 Cost:  10.89096 
Prediction:
 [[154.40344]
 [185.18762]
 [182.8803 ]
 [189.90439]
 [143.7862 ]]
2020 Cost:  10.859795 
Prediction:
 [[154.39325]
 [185.1908 ]
 [182.87518]
 [189.91183]
 [143.78955]]
2030 Cost:  10.828751 
Prediction:
 [[154.38309]
 [185.19394]
 [182.8701 ]
 [189.91928]
 [143.79288]]
2040 Cost:  10.797872 
Prediction:
 [[154.37294]
 [185.19708]
 [182.865  ]
 [189.9267 ]
 [143.79622]]
2050 Cost:  10.76721 
Prediction:
 [[154.36287]
 [185.20021]
 [182.85999]
 [189.93411]
 [143.79953]]
2060 Cost:  10.7366495 
Prediction:
 [[154.3528 ]
 [185.20334]
 [182.8549 ]
 [189.94148]
 [143.80281]]
2070 Cost:  10.706246 
Prediction:
 [[154.34274]
 [185.20642]
 [182.84987]
 [189.94884]
 [143.80606]]
2080 Cost:  10.675974 
Prediction:
 [[154.33275]
 [185.20952]
 [182.84485]
 [189.9562 ]
 [143.80933]]
2090 Cost:  10.645951 
Prediction:
 [[154.32278]
 [185.2126 ]
 [182.83984]
 [189.96

2820 Cost:  8.821032 
Prediction:
 [[153.67535]
 [185.41008]
 [182.51265]
 [190.45247]
 [144.01039]]
2830 Cost:  8.800397 
Prediction:
 [[153.6675 ]
 [185.41245]
 [182.50865]
 [190.45857]
 [144.0126 ]]
2840 Cost:  8.779813 
Prediction:
 [[153.65967]
 [185.41481]
 [182.50467]
 [190.46469]
 [144.01482]]
2850 Cost:  8.759372 
Prediction:
 [[153.65187]
 [185.41711]
 [182.5007 ]
 [190.47078]
 [144.01703]]
2860 Cost:  8.739027 
Prediction:
 [[153.64412]
 [185.41946]
 [182.49673]
 [190.47685]
 [144.01921]]
2870 Cost:  8.718743 
Prediction:
 [[153.63634]
 [185.42178]
 [182.49278]
 [190.48291]
 [144.02138]]
2880 Cost:  8.698596 
Prediction:
 [[153.62862]
 [185.4241 ]
 [182.48885]
 [190.48895]
 [144.02354]]
2890 Cost:  8.678513 
Prediction:
 [[153.62091]
 [185.42639]
 [182.48491]
 [190.49498]
 [144.02568]]
2900 Cost:  8.658606 
Prediction:
 [[153.61325]
 [185.42871]
 [182.48099]
 [190.50098]
 [144.02783]]
2910 Cost:  8.638688 
Prediction:
 [[153.6056 ]
 [185.43102]
 [182.47711]
 [190.50702]
 [14

3870 Cost:  7.100974 
Prediction:
 [[152.97554]
 [185.61565]
 [182.15227]
 [191.02333]
 [144.1851 ]]
3880 Cost:  7.0881376 
Prediction:
 [[152.96997]
 [185.61723]
 [182.14937]
 [191.02815]
 [144.18628]]
3890 Cost:  7.075339 
Prediction:
 [[152.96439]
 [185.6188 ]
 [182.14645]
 [191.03294]
 [144.18742]]
3900 Cost:  7.0626006 
Prediction:
 [[152.95885]
 [185.62039]
 [182.14355]
 [191.03773]
 [144.18857]]
3910 Cost:  7.04992 
Prediction:
 [[152.95331]
 [185.62196]
 [182.14066]
 [191.0425 ]
 [144.18968]]
3920 Cost:  7.037262 
Prediction:
 [[152.94778]
 [185.62354]
 [182.13779]
 [191.04729]
 [144.19083]]
3930 Cost:  7.0246763 
Prediction:
 [[152.94229]
 [185.62509]
 [182.13489]
 [191.05203]
 [144.19194]]
3940 Cost:  7.012137 
Prediction:
 [[152.93683]
 [185.62665]
 [182.13203]
 [191.0568 ]
 [144.19305]]
3950 Cost:  6.9996643 
Prediction:
 [[152.93135]
 [185.6282 ]
 [182.12918]
 [191.06152]
 [144.19415]]
3960 Cost:  6.987237 
Prediction:
 [[152.92593]
 [185.62976]
 [182.12634]
 [191.06627]
 

4720 Cost:  6.1713696 
Prediction:
 [[152.56003]
 [185.73108]
 [181.93268]
 [191.39754]
 [144.25629]]
4730 Cost:  6.162069 
Prediction:
 [[152.5558 ]
 [185.73222]
 [181.93044]
 [191.40158]
 [144.25682]]
4740 Cost:  6.1528306 
Prediction:
 [[152.55159]
 [185.73335]
 [181.92816]
 [191.4056 ]
 [144.25737]]
4750 Cost:  6.1436496 
Prediction:
 [[152.54736]
 [185.7345 ]
 [181.9259 ]
 [191.40958]
 [144.25789]]
4760 Cost:  6.134471 
Prediction:
 [[152.54318]
 [185.73561]
 [181.92365]
 [191.41357]
 [144.25842]]
4770 Cost:  6.125313 
Prediction:
 [[152.53902]
 [185.73674]
 [181.92142]
 [191.41757]
 [144.25893]]
4780 Cost:  6.1162453 
Prediction:
 [[152.53482]
 [185.73785]
 [181.91917]
 [191.42152]
 [144.25945]]
4790 Cost:  6.107136 
Prediction:
 [[152.53065]
 [185.73894]
 [181.91693]
 [191.42549]
 [144.25993]]
4800 Cost:  6.0981064 
Prediction:
 [[152.52654]
 [185.74008]
 [181.91472]
 [191.42946]
 [144.26044]]
4810 Cost:  6.0890975 
Prediction:
 [[152.5224 ]
 [185.74115]
 [181.91249]
 [191.4334 

 [144.28238]]
5640 Cost:  5.4346056 
Prediction:
 [[152.22272]
 [185.8184 ]
 [181.74901]
 [191.7356 ]
 [144.28242]]
5650 Cost:  5.427676 
Prediction:
 [[152.21959]
 [185.81918]
 [181.74725]
 [191.73897]
 [144.2825 ]]
5660 Cost:  5.4207683 
Prediction:
 [[152.21646]
 [185.81995]
 [181.74554]
 [191.74232]
 [144.28253]]
5670 Cost:  5.4139 
Prediction:
 [[152.21335]
 [185.8207 ]
 [181.74379]
 [191.74565]
 [144.28258]]
5680 Cost:  5.4070396 
Prediction:
 [[152.21025]
 [185.82149]
 [181.74207]
 [191.749  ]
 [144.28261]]
5690 Cost:  5.400192 
Prediction:
 [[152.20714]
 [185.82225]
 [181.74034]
 [191.75233]
 [144.28265]]
5700 Cost:  5.3934045 
Prediction:
 [[152.20406]
 [185.82301]
 [181.73863]
 [191.75565]
 [144.28268]]
5710 Cost:  5.38656 
Prediction:
 [[152.20096]
 [185.82373]
 [181.73691]
 [191.75897]
 [144.2827 ]]
5720 Cost:  5.379821 
Prediction:
 [[152.19789]
 [185.82446]
 [181.7352 ]
 [191.76225]
 [144.28271]]
5730 Cost:  5.3730507 
Prediction:
 [[152.19484]
 [185.82523]
 [181.73349]
 

6560 Cost:  4.869638 
Prediction:
 [[151.97302]
 [185.87666]
 [181.6076 ]
 [192.02   ]
 [144.27028]]
6570 Cost:  4.864174 
Prediction:
 [[151.9707 ]
 [185.87717]
 [181.60626]
 [192.02286]
 [144.26999]]
6580 Cost:  4.8587356 
Prediction:
 [[151.9684 ]
 [185.87767]
 [181.60493]
 [192.0257 ]
 [144.26968]]
6590 Cost:  4.8532934 
Prediction:
 [[151.96608]
 [185.87816]
 [181.60356]
 [192.02852]
 [144.26938]]
6600 Cost:  4.8478594 
Prediction:
 [[151.96378]
 [185.87868]
 [181.60223]
 [192.03136]
 [144.26906]]
6610 Cost:  4.8424425 
Prediction:
 [[151.9615 ]
 [185.87915]
 [181.60089]
 [192.03418]
 [144.26875]]
6620 Cost:  4.837039 
Prediction:
 [[151.9592 ]
 [185.87962]
 [181.59956]
 [192.03699]
 [144.26842]]
6630 Cost:  4.83167 
Prediction:
 [[151.95692]
 [185.88014]
 [181.59825]
 [192.03981]
 [144.26811]]
6640 Cost:  4.8262963 
Prediction:
 [[151.95467]
 [185.88063]
 [181.59694]
 [192.04263]
 [144.2678 ]]
6650 Cost:  4.8209114 
Prediction:
 [[151.9524 ]
 [185.8811 ]
 [181.5956 ]
 [192.04543]

7460 Cost:  4.4220495 
Prediction:
 [[151.79193]
 [185.91295]
 [181.49997]
 [192.25813]
 [144.23204]]
7470 Cost:  4.417529 
Prediction:
 [[151.79019]
 [185.91328]
 [181.49893]
 [192.26059]
 [144.23149]]
7480 Cost:  4.412989 
Prediction:
 [[151.78848]
 [185.91357]
 [181.49786]
 [192.26305]
 [144.23096]]
7490 Cost:  4.4084635 
Prediction:
 [[151.78677]
 [185.91388]
 [181.49683]
 [192.2655 ]
 [144.23041]]
7500 Cost:  4.4039636 
Prediction:
 [[151.78506]
 [185.91417]
 [181.49577]
 [192.26794]
 [144.22987]]
7510 Cost:  4.3994513 
Prediction:
 [[151.78336]
 [185.91449]
 [181.49474]
 [192.2704 ]
 [144.22932]]
7520 Cost:  4.3949447 
Prediction:
 [[151.78166]
 [185.91478]
 [181.49368]
 [192.27284]
 [144.22878]]
7530 Cost:  4.3904877 
Prediction:
 [[151.77998]
 [185.91508]
 [181.49265]
 [192.27525]
 [144.22821]]
7540 Cost:  4.3859916 
Prediction:
 [[151.77827]
 [185.91539]
 [181.49161]
 [192.2777 ]
 [144.22765]]
7550 Cost:  4.381522 
Prediction:
 [[151.7766 ]
 [185.91566]
 [181.49057]
 [192.2801

8500 Cost:  3.9899132 
Prediction:
 [[151.63995]
 [185.93645]
 [181.40373]
 [192.49529]
 [144.16553]]
8510 Cost:  3.986091 
Prediction:
 [[151.63872]
 [185.93658]
 [181.40294]
 [192.4974 ]
 [144.1648 ]]
8520 Cost:  3.9822793 
Prediction:
 [[151.6375 ]
 [185.93674]
 [181.40211]
 [192.49951]
 [144.16406]]
8530 Cost:  3.9784794 
Prediction:
 [[151.63629]
 [185.93687]
 [181.40132]
 [192.50162]
 [144.16333]]
8540 Cost:  3.9747071 
Prediction:
 [[151.63509]
 [185.93704]
 [181.40053]
 [192.50372]
 [144.16261]]
8550 Cost:  3.9708946 
Prediction:
 [[151.63387]
 [185.93715]
 [181.3997 ]
 [192.50581]
 [144.16187]]
8560 Cost:  3.9671159 
Prediction:
 [[151.63268]
 [185.9373 ]
 [181.39893]
 [192.50792]
 [144.16113]]
8570 Cost:  3.9633305 
Prediction:
 [[151.63148]
 [185.93745]
 [181.39813]
 [192.51003]
 [144.1604 ]]
8580 Cost:  3.9595666 
Prediction:
 [[151.6303 ]
 [185.93758]
 [181.39734]
 [192.5121 ]
 [144.15965]]
8590 Cost:  3.9558063 
Prediction:
 [[151.62912]
 [185.93773]
 [181.39656]
 [192.51

9450 Cost:  3.6508355 
Prediction:
 [[151.54047]
 [185.94551]
 [181.33539]
 [192.68427]
 [144.09085]]
9460 Cost:  3.6474824 
Prediction:
 [[151.53957]
 [185.94553]
 [181.33475]
 [192.68613]
 [144.09   ]]
9470 Cost:  3.644135 
Prediction:
 [[151.5387 ]
 [185.94559]
 [181.3341 ]
 [192.688  ]
 [144.08916]]
9480 Cost:  3.6408126 
Prediction:
 [[151.53781]
 [185.94565]
 [181.33347]
 [192.68987]
 [144.08832]]
9490 Cost:  3.6375053 
Prediction:
 [[151.53694]
 [185.9457 ]
 [181.33284]
 [192.69173]
 [144.0875 ]]
9500 Cost:  3.6341782 
Prediction:
 [[151.53604]
 [185.94572]
 [181.33218]
 [192.69357]
 [144.08664]]
9510 Cost:  3.6308331 
Prediction:
 [[151.53519]
 [185.94576]
 [181.33156]
 [192.69545]
 [144.0858 ]]
9520 Cost:  3.6275184 
Prediction:
 [[151.53432]
 [185.9458 ]
 [181.33092]
 [192.6973 ]
 [144.08495]]
9530 Cost:  3.624197 
Prediction:
 [[151.53343]
 [185.94582]
 [181.33028]
 [192.69914]
 [144.08409]]
9540 Cost:  3.6208777 
Prediction:
 [[151.5326 ]
 [185.94586]
 [181.32968]
 [192.701

10480 Cost:  3.3274236 
Prediction:
 [[151.4633 ]
 [185.94597]
 [181.27676]
 [192.86595]
 [144.00046]]
10490 Cost:  3.3244922 
Prediction:
 [[151.46268]
 [185.9459 ]
 [181.27626]
 [192.8676 ]
 [143.99956]]
10500 Cost:  3.3215203 
Prediction:
 [[151.46207]
 [185.94588]
 [181.27576]
 [192.86928]
 [143.99864]]
10510 Cost:  3.3185658 
Prediction:
 [[151.46144]
 [185.94585]
 [181.27525]
 [192.87096]
 [143.99774]]
10520 Cost:  3.3156261 
Prediction:
 [[151.46082]
 [185.94582]
 [181.27475]
 [192.8726 ]
 [143.99681]]
10530 Cost:  3.3126807 
Prediction:
 [[151.4602 ]
 [185.94577]
 [181.27426]
 [192.87427]
 [143.9959 ]]
10540 Cost:  3.309766 
Prediction:
 [[151.4596 ]
 [185.94574]
 [181.27376]
 [192.87592]
 [143.995  ]]
10550 Cost:  3.306841 
Prediction:
 [[151.45898]
 [185.94571]
 [181.27325]
 [192.87756]
 [143.99408]]
10560 Cost:  3.3038993 
Prediction:
 [[151.45837]
 [185.94566]
 [181.27275]
 [192.87921]
 [143.99315]]
10570 Cost:  3.3009858 
Prediction:
 [[151.45776]
 [185.94563]
 [181.27228]

11340 Cost:  3.0855467 
Prediction:
 [[151.41681]
 [185.94109]
 [181.23709]
 [193.0029 ]
 [143.92067]]
11350 Cost:  3.0828795 
Prediction:
 [[151.41637]
 [185.94102]
 [181.23668]
 [193.00443]
 [143.91974]]
11360 Cost:  3.0801926 
Prediction:
 [[151.41588]
 [185.94093]
 [181.23624]
 [193.00594]
 [143.91878]]
11370 Cost:  3.0775042 
Prediction:
 [[151.41544]
 [185.94086]
 [181.23582]
 [193.00748]
 [143.91785]]
11380 Cost:  3.074843 
Prediction:
 [[151.415  ]
 [185.94078]
 [181.23543]
 [193.009  ]
 [143.91692]]
11390 Cost:  3.072176 
Prediction:
 [[151.41452]
 [185.94067]
 [181.23499]
 [193.01048]
 [143.91594]]
11400 Cost:  3.069503 
Prediction:
 [[151.41406]
 [185.9406 ]
 [181.23459]
 [193.01202]
 [143.91501]]
11410 Cost:  3.0668445 
Prediction:
 [[151.41362]
 [185.94054]
 [181.23418]
 [193.01355]
 [143.91408]]
11420 Cost:  3.064178 
Prediction:
 [[151.41316]
 [185.94044]
 [181.23375]
 [193.01506]
 [143.91313]]
11430 Cost:  3.061541 
Prediction:
 [[151.41272]
 [185.94037]
 [181.23334]
 [

12390 Cost:  2.819034 
Prediction:
 [[151.3762 ]
 [185.93073]
 [181.1972 ]
 [193.15541]
 [143.82066]]
12400 Cost:  2.8166182 
Prediction:
 [[151.37587]
 [185.93059]
 [181.19684]
 [193.15678]
 [143.81969]]
12410 Cost:  2.814238 
Prediction:
 [[151.37555]
 [185.93048]
 [181.19652]
 [193.15817]
 [143.81874]]
12420 Cost:  2.8118408 
Prediction:
 [[151.37524]
 [185.93036]
 [181.19617]
 [193.15955]
 [143.81778]]
12430 Cost:  2.8094501 
Prediction:
 [[151.37492]
 [185.93024]
 [181.19583]
 [193.16093]
 [143.81683]]
12440 Cost:  2.8070526 
Prediction:
 [[151.3746 ]
 [185.9301 ]
 [181.19547]
 [193.1623 ]
 [143.81586]]
12450 Cost:  2.8046696 
Prediction:
 [[151.3743 ]
 [185.93   ]
 [181.19516]
 [193.16368]
 [143.8149 ]]
12460 Cost:  2.8022563 
Prediction:
 [[151.37401]
 [185.92987]
 [181.19481]
 [193.16507]
 [143.81393]]
12470 Cost:  2.7998958 
Prediction:
 [[151.3737 ]
 [185.92976]
 [181.19447]
 [193.16643]
 [143.81297]]
12480 Cost:  2.7975144 
Prediction:
 [[151.37337]
 [185.92963]
 [181.19412]

13400 Cost:  2.5883737 
Prediction:
 [[151.34933]
 [185.9176 ]
 [181.16553]
 [193.28954]
 [143.72379]]
13410 Cost:  2.5861917 
Prediction:
 [[151.34912]
 [185.91747]
 [181.16524]
 [193.29082]
 [143.72282]]
13420 Cost:  2.5840273 
Prediction:
 [[151.3489 ]
 [185.91733]
 [181.16495]
 [193.29208]
 [143.72186]]
13430 Cost:  2.5818746 
Prediction:
 [[151.3487 ]
 [185.91719]
 [181.16466]
 [193.29335]
 [143.72092]]
13440 Cost:  2.5797207 
Prediction:
 [[151.34848]
 [185.91705]
 [181.1644 ]
 [193.29463]
 [143.71997]]
13450 Cost:  2.5775404 
Prediction:
 [[151.34825]
 [185.9169 ]
 [181.1641 ]
 [193.2959 ]
 [143.719  ]]
13460 Cost:  2.5754037 
Prediction:
 [[151.34804]
 [185.91678]
 [181.16382]
 [193.29716]
 [143.71805]]
13470 Cost:  2.573229 
Prediction:
 [[151.34784]
 [185.91663]
 [181.16353]
 [193.29845]
 [143.7171 ]]
13480 Cost:  2.571078 
Prediction:
 [[151.34763]
 [185.91649]
 [181.16325]
 [193.29971]
 [143.71614]]
13490 Cost:  2.5689387 
Prediction:
 [[151.34741]
 [185.91635]
 [181.16298]

14380 Cost:  2.3856308 
Prediction:
 [[151.3315 ]
 [185.90306]
 [181.13951]
 [193.40994]
 [143.6306 ]]
14390 Cost:  2.3836732 
Prediction:
 [[151.33134]
 [185.90291]
 [181.13924]
 [193.4111 ]
 [143.62965]]
14400 Cost:  2.3817017 
Prediction:
 [[151.3312 ]
 [185.90277]
 [181.139  ]
 [193.41231]
 [143.62872]]
14410 Cost:  2.379736 
Prediction:
 [[151.33104]
 [185.90259]
 [181.13875]
 [193.41347]
 [143.62776]]
14420 Cost:  2.377769 
Prediction:
 [[151.33089]
 [185.90245]
 [181.1385 ]
 [193.41466]
 [143.62682]]
14430 Cost:  2.375811 
Prediction:
 [[151.33075]
 [185.90228]
 [181.13828]
 [193.41583]
 [143.62587]]
14440 Cost:  2.3738534 
Prediction:
 [[151.33058]
 [185.90213]
 [181.13802]
 [193.417  ]
 [143.62492]]
14450 Cost:  2.3718913 
Prediction:
 [[151.33044]
 [185.90196]
 [181.13779]
 [193.4182 ]
 [143.624  ]]
14460 Cost:  2.3699486 
Prediction:
 [[151.3303 ]
 [185.90182]
 [181.13753]
 [193.41936]
 [143.62305]]
14470 Cost:  2.3679628 
Prediction:
 [[151.33017]
 [185.90166]
 [181.1373 ]


15410 Cost:  2.192438 
Prediction:
 [[151.31897]
 [185.88663]
 [181.11594]
 [193.52768]
 [143.53447]]
15420 Cost:  2.1906707 
Prediction:
 [[151.31886]
 [185.88646]
 [181.11574]
 [193.52878]
 [143.53355]]
15430 Cost:  2.188868 
Prediction:
 [[151.31877]
 [185.8863 ]
 [181.11551]
 [193.52989]
 [143.53262]]
15440 Cost:  2.1870892 
Prediction:
 [[151.3187 ]
 [185.88612]
 [181.11531]
 [193.53099]
 [143.53171]]
15450 Cost:  2.18531 
Prediction:
 [[151.3186 ]
 [185.88597]
 [181.1151 ]
 [193.53209]
 [143.53078]]
15460 Cost:  2.1835341 
Prediction:
 [[151.3185 ]
 [185.88579]
 [181.11488]
 [193.53319]
 [143.52986]]
15470 Cost:  2.1817727 
Prediction:
 [[151.3184 ]
 [185.88564]
 [181.11469]
 [193.53429]
 [143.52895]]
15480 Cost:  2.179986 
Prediction:
 [[151.31833]
 [185.88548]
 [181.11447]
 [193.5354 ]
 [143.52803]]
15490 Cost:  2.1782088 
Prediction:
 [[151.31822]
 [185.88531]
 [181.11426]
 [193.5365 ]
 [143.5271 ]]
15500 Cost:  2.1764677 
Prediction:
 [[151.31813]
 [185.88516]
 [181.11404]
 [

16440 Cost:  2.0174835 
Prediction:
 [[151.31105]
 [185.86958]
 [181.09538]
 [193.6377 ]
 [143.44092]]
16450 Cost:  2.0158865 
Prediction:
 [[151.31099]
 [185.8694 ]
 [181.0952 ]
 [193.6387 ]
 [143.44002]]
16460 Cost:  2.0142639 
Prediction:
 [[151.31091]
 [185.86923]
 [181.095  ]
 [193.63974]
 [143.43912]]
16470 Cost:  2.0126615 
Prediction:
 [[151.31087]
 [185.86908]
 [181.09483]
 [193.64078]
 [143.43823]]
16480 Cost:  2.0110507 
Prediction:
 [[151.3108 ]
 [185.86891]
 [181.09464]
 [193.6418 ]
 [143.43733]]
16490 Cost:  2.0094473 
Prediction:
 [[151.31075]
 [185.86874]
 [181.09445]
 [193.64282]
 [143.43643]]
16500 Cost:  2.0078325 
Prediction:
 [[151.31068]
 [185.86858]
 [181.09425]
 [193.64386]
 [143.43555]]
16510 Cost:  2.006221 
Prediction:
 [[151.31064]
 [185.86841]
 [181.09407]
 [193.6449 ]
 [143.43466]]
16520 Cost:  2.0046277 
Prediction:
 [[151.3106 ]
 [185.86827]
 [181.0939 ]
 [193.64594]
 [143.43378]]
16530 Cost:  2.0030162 
Prediction:
 [[151.31053]
 [185.86809]
 [181.09372

17490 Cost:  1.8560766 
Prediction:
 [[151.3063 ]
 [185.85204]
 [181.07683]
 [193.74284]
 [143.34866]]
17500 Cost:  1.8546188 
Prediction:
 [[151.30627]
 [185.85187]
 [181.07666]
 [193.7438 ]
 [143.3478 ]]
17510 Cost:  1.8531605 
Prediction:
 [[151.30623]
 [185.8517 ]
 [181.07649]
 [193.74478]
 [143.34694]]
17520 Cost:  1.8517027 
Prediction:
 [[151.3062 ]
 [185.85155]
 [181.07631]
 [193.74574]
 [143.34607]]
17530 Cost:  1.8502483 
Prediction:
 [[151.30617]
 [185.85136]
 [181.07616]
 [193.7467 ]
 [143.3452 ]]
17540 Cost:  1.8487974 
Prediction:
 [[151.30612]
 [185.8512 ]
 [181.07599]
 [193.74767]
 [143.34433]]
17550 Cost:  1.8473198 
Prediction:
 [[151.3061 ]
 [185.85103]
 [181.07582]
 [193.74866]
 [143.34348]]
17560 Cost:  1.8458761 
Prediction:
 [[151.30609]
 [185.85088]
 [181.07567]
 [193.74963]
 [143.34264]]
17570 Cost:  1.8444233 
Prediction:
 [[151.30606]
 [185.85071]
 [181.0755 ]
 [193.7506 ]
 [143.34177]]
17580 Cost:  1.8429836 
Prediction:
 [[151.30602]
 [185.85054]
 [181.0753

18350 Cost:  1.7353961 
Prediction:
 [[151.3042 ]
 [185.83774]
 [181.06305]
 [193.82428]
 [143.27562]]
18360 Cost:  1.7340492 
Prediction:
 [[151.30418]
 [185.83757]
 [181.0629 ]
 [193.82521]
 [143.2748 ]]
18370 Cost:  1.7327001 
Prediction:
 [[151.30417]
 [185.83742]
 [181.06274]
 [193.82614]
 [143.27396]]
18380 Cost:  1.731362 
Prediction:
 [[151.30417]
 [185.83725]
 [181.0626 ]
 [193.82706]
 [143.27312]]
18390 Cost:  1.7300146 
Prediction:
 [[151.30414]
 [185.83708]
 [181.06244]
 [193.82799]
 [143.2723 ]]
18400 Cost:  1.72868 
Prediction:
 [[151.30411]
 [185.83691]
 [181.06229]
 [193.8289 ]
 [143.27145]]
18410 Cost:  1.7273228 
Prediction:
 [[151.30411]
 [185.83676]
 [181.06212]
 [193.82983]
 [143.27061]]
18420 Cost:  1.7259941 
Prediction:
 [[151.3041 ]
 [185.83658]
 [181.06198]
 [193.83075]
 [143.26979]]
18430 Cost:  1.7246797 
Prediction:
 [[151.30406]
 [185.83643]
 [181.06183]
 [193.83165]
 [143.26895]]
18440 Cost:  1.7233185 
Prediction:
 [[151.30405]
 [185.83624]
 [181.06166]


19410 Cost:  1.5996357 
Prediction:
 [[151.30319]
 [185.82037]
 [181.0475 ]
 [193.91939]
 [143.18887]]
19420 Cost:  1.5984209 
Prediction:
 [[151.30319]
 [185.82022]
 [181.04738]
 [193.92027]
 [143.18808]]
19430 Cost:  1.5972053 
Prediction:
 [[151.30319]
 [185.82008]
 [181.04724]
 [193.92116]
 [143.18729]]
19440 Cost:  1.5959857 
Prediction:
 [[151.30319]
 [185.81992]
 [181.0471 ]
 [193.92203]
 [143.18648]]
19450 Cost:  1.5947771 
Prediction:
 [[151.30318]
 [185.81975]
 [181.04695]
 [193.92288]
 [143.18567]]
19460 Cost:  1.5935528 
Prediction:
 [[151.30318]
 [185.8196 ]
 [181.04681]
 [193.92378]
 [143.18489]]
19470 Cost:  1.5923603 
Prediction:
 [[151.30318]
 [185.81943]
 [181.04668]
 [193.92462]
 [143.18408]]
19480 Cost:  1.591125 
Prediction:
 [[151.30318]
 [185.81926]
 [181.04654]
 [193.92552]
 [143.18329]]
19490 Cost:  1.5899314 
Prediction:
 [[151.30316]
 [185.81909]
 [181.04639]
 [193.92636]
 [143.18248]]
19500 Cost:  1.5887339 
Prediction:
 [[151.30316]
 [185.81894]
 [181.04626

20430 Cost:  1.4813054 
Prediction:
 [[151.30338]
 [185.80412]
 [181.0338 ]
 [194.00594]
 [143.10887]]
20440 Cost:  1.4802055 
Prediction:
 [[151.30338]
 [185.80396]
 [181.03368]
 [194.00676]
 [143.10811]]
20450 Cost:  1.4790938 
Prediction:
 [[151.30338]
 [185.80379]
 [181.03352]
 [194.00758]
 [143.10735]]
20460 Cost:  1.4780004 
Prediction:
 [[151.30339]
 [185.80365]
 [181.0334 ]
 [194.0084 ]
 [143.10658]]
20470 Cost:  1.4769012 
Prediction:
 [[151.30339]
 [185.80348]
 [181.03326]
 [194.00922]
 [143.1058 ]]
20480 Cost:  1.4757845 
Prediction:
 [[151.30339]
 [185.80331]
 [181.03314]
 [194.01006]
 [143.10503]]
20490 Cost:  1.4747016 
Prediction:
 [[151.30342]
 [185.80318]
 [181.03304]
 [194.01088]
 [143.10428]]
20500 Cost:  1.47358 
Prediction:
 [[151.30342]
 [185.80301]
 [181.0329 ]
 [194.01172]
 [143.1035 ]]
20510 Cost:  1.4724886 
Prediction:
 [[151.30342]
 [185.80286]
 [181.03278]
 [194.01254]
 [143.10274]]
20520 Cost:  1.4714009 
Prediction:
 [[151.30344]
 [185.80269]
 [181.03265]

21450 Cost:  1.3739088 
Prediction:
 [[151.30434]
 [185.78835]
 [181.0211 ]
 [194.08797]
 [143.03227]]
21460 Cost:  1.3729126 
Prediction:
 [[151.30434]
 [185.7882 ]
 [181.02097]
 [194.08873]
 [143.03152]]
21470 Cost:  1.371897 
Prediction:
 [[151.30435]
 [185.78802]
 [181.02084]
 [194.08952]
 [143.03079]]
21480 Cost:  1.3709031 
Prediction:
 [[151.30437]
 [185.78789]
 [181.02074]
 [194.0903 ]
 [143.03004]]
21490 Cost:  1.3699112 
Prediction:
 [[151.30438]
 [185.78773]
 [181.02061]
 [194.09108]
 [143.02933]]
21500 Cost:  1.3688971 
Prediction:
 [[151.30441]
 [185.7876 ]
 [181.02051]
 [194.09189]
 [143.0286 ]]
21510 Cost:  1.3679041 
Prediction:
 [[151.30441]
 [185.78745]
 [181.02039]
 [194.09267]
 [143.02786]]
21520 Cost:  1.3668963 
Prediction:
 [[151.30443]
 [185.78728]
 [181.02026]
 [194.09344]
 [143.02711]]
21530 Cost:  1.3659117 
Prediction:
 [[151.30444]
 [185.78712]
 [181.02013]
 [194.09421]
 [143.0264 ]]
21540 Cost:  1.3649263 
Prediction:
 [[151.30444]
 [185.78697]
 [181.02002

22460 Cost:  1.2773312 
Prediction:
 [[151.3058 ]
 [185.77325]
 [181.00937]
 [194.16507]
 [142.9597 ]]
22470 Cost:  1.2764213 
Prediction:
 [[151.3058 ]
 [185.7731 ]
 [181.00923]
 [194.16579]
 [142.95897]]
22480 Cost:  1.2755105 
Prediction:
 [[151.30583]
 [185.77296]
 [181.00914]
 [194.16655]
 [142.95828]]
22490 Cost:  1.2746078 
Prediction:
 [[151.30583]
 [185.77283]
 [181.00903]
 [194.1673 ]
 [142.95758]]
22500 Cost:  1.2736973 
Prediction:
 [[151.30586]
 [185.77267]
 [181.00891]
 [194.16803]
 [142.95688]]
22510 Cost:  1.2727927 
Prediction:
 [[151.3059 ]
 [185.77254]
 [181.0088 ]
 [194.16878]
 [142.95619]]
22520 Cost:  1.2718976 
Prediction:
 [[151.3059 ]
 [185.7724 ]
 [181.00871]
 [194.16953]
 [142.95549]]
22530 Cost:  1.2709849 
Prediction:
 [[151.30594]
 [185.77225]
 [181.0086 ]
 [194.17027]
 [142.9548 ]]
22540 Cost:  1.2700733 
Prediction:
 [[151.30594]
 [185.7721 ]
 [181.00848]
 [194.17102]
 [142.9541 ]]
22550 Cost:  1.2691743 
Prediction:
 [[151.30595]
 [185.77196]
 [181.0083

23430 Cost:  1.1929128 
Prediction:
 [[151.30753]
 [185.75931]
 [180.9988 ]
 [194.2355 ]
 [142.893  ]]
23440 Cost:  1.1920846 
Prediction:
 [[151.30754]
 [185.75917]
 [180.9987 ]
 [194.23622]
 [142.89233]]
23450 Cost:  1.1912551 
Prediction:
 [[151.30756]
 [185.75903]
 [180.99858]
 [194.23692]
 [142.89166]]
23460 Cost:  1.1904215 
Prediction:
 [[151.30757]
 [185.7589 ]
 [180.99847]
 [194.23764]
 [142.89099]]
23470 Cost:  1.189601 
Prediction:
 [[151.3076 ]
 [185.75876]
 [180.99838]
 [194.23834]
 [142.89032]]
23480 Cost:  1.1887643 
Prediction:
 [[151.30762]
 [185.7586 ]
 [180.99829]
 [194.23907]
 [142.88966]]
23490 Cost:  1.1879519 
Prediction:
 [[151.30763]
 [185.75848]
 [180.99817]
 [194.23976]
 [142.88899]]
23500 Cost:  1.1871225 
Prediction:
 [[151.30766]
 [185.75833]
 [180.99808]
 [194.24048]
 [142.88834]]
23510 Cost:  1.1862901 
Prediction:
 [[151.30768]
 [185.7582 ]
 [180.99796]
 [194.24118]
 [142.88765]]
23520 Cost:  1.1854737 
Prediction:
 [[151.30768]
 [185.75806]
 [180.99785

24390 Cost:  1.1166875 
Prediction:
 [[151.30942]
 [185.74603]
 [180.98892]
 [194.30196]
 [142.82985]]
24400 Cost:  1.1159327 
Prediction:
 [[151.30943]
 [185.7459 ]
 [180.98883]
 [194.30263]
 [142.8292 ]]
24410 Cost:  1.1151724 
Prediction:
 [[151.30945]
 [185.74574]
 [180.98872]
 [194.3033 ]
 [142.82855]]
24420 Cost:  1.114413 
Prediction:
 [[151.30948]
 [185.74562]
 [180.98863]
 [194.30399]
 [142.82791]]
24430 Cost:  1.1136429 
Prediction:
 [[151.30951]
 [185.7455 ]
 [180.98853]
 [194.30469]
 [142.82729]]
24440 Cost:  1.1128993 
Prediction:
 [[151.30951]
 [185.74535]
 [180.98843]
 [194.30534]
 [142.82663]]
24450 Cost:  1.1121604 
Prediction:
 [[151.30952]
 [185.74521]
 [180.98833]
 [194.306  ]
 [142.826  ]]
24460 Cost:  1.1113913 
Prediction:
 [[151.30954]
 [185.74507]
 [180.98822]
 [194.30669]
 [142.82535]]
24470 Cost:  1.1106341 
Prediction:
 [[151.30959]
 [185.74496]
 [180.98813]
 [194.30737]
 [142.8247 ]]
24480 Cost:  1.109897 
Prediction:
 [[151.3096 ]
 [185.74481]
 [180.98802]

25340 Cost:  1.0477781 
Prediction:
 [[151.3114 ]
 [185.7334 ]
 [180.97968]
 [194.36472]
 [142.77002]]
25350 Cost:  1.047086 
Prediction:
 [[151.31142]
 [185.73326]
 [180.97958]
 [194.36536]
 [142.7694 ]]
25360 Cost:  1.0464032 
Prediction:
 [[151.31145]
 [185.73314]
 [180.97948]
 [194.36598]
 [142.76878]]
25370 Cost:  1.0457065 
Prediction:
 [[151.31146]
 [185.733  ]
 [180.97939]
 [194.36664]
 [142.76817]]
25380 Cost:  1.0450156 
Prediction:
 [[151.3115 ]
 [185.73288]
 [180.9793 ]
 [194.36728]
 [142.76755]]
25390 Cost:  1.0443399 
Prediction:
 [[151.31151]
 [185.73276]
 [180.97922]
 [194.36792]
 [142.76694]]
25400 Cost:  1.04363 
Prediction:
 [[151.31154]
 [185.73262]
 [180.97913]
 [194.36859]
 [142.76633]]
25410 Cost:  1.042948 
Prediction:
 [[151.31154]
 [185.73248]
 [180.97902]
 [194.36922]
 [142.7657 ]]
25420 Cost:  1.0422589 
Prediction:
 [[151.31157]
 [185.73235]
 [180.97893]
 [194.36986]
 [142.76509]]
25430 Cost:  1.041568 
Prediction:
 [[151.31158]
 [185.73221]
 [180.97882]
 [

26320 Cost:  0.9829218 
Prediction:
 [[151.31349]
 [185.7209 ]
 [180.97063]
 [194.42647]
 [142.71098]]
26330 Cost:  0.9822938 
Prediction:
 [[151.31352]
 [185.72078]
 [180.97054]
 [194.42708]
 [142.7104 ]]
26340 Cost:  0.98168075 
Prediction:
 [[151.31354]
 [185.72064]
 [180.97044]
 [194.42766]
 [142.70981]]
26350 Cost:  0.9810357 
Prediction:
 [[151.31357]
 [185.72052]
 [180.97037]
 [194.4283 ]
 [142.70921]]
26360 Cost:  0.980412 
Prediction:
 [[151.31358]
 [185.7204 ]
 [180.97026]
 [194.4289 ]
 [142.70862]]
26370 Cost:  0.9797757 
Prediction:
 [[151.31361]
 [185.72028]
 [180.97017]
 [194.42952]
 [142.70804]]
26380 Cost:  0.97914535 
Prediction:
 [[151.31364]
 [185.72015]
 [180.9701 ]
 [194.43015]
 [142.70746]]
26390 Cost:  0.97852314 
Prediction:
 [[151.31364]
 [185.72002]
 [180.97   ]
 [194.43076]
 [142.70688]]
26400 Cost:  0.9778929 
Prediction:
 [[151.31367]
 [185.7199 ]
 [180.96991]
 [194.43137]
 [142.70628]]
26410 Cost:  0.9772714 
Prediction:
 [[151.31369]
 [185.71977]
 [180.96

27240 Cost:  0.9272979 
Prediction:
 [[151.3155 ]
 [185.70964]
 [180.96257]
 [194.48181]
 [142.65797]]
27250 Cost:  0.9267174 
Prediction:
 [[151.31552]
 [185.70952]
 [180.96246]
 [194.48239]
 [142.65741]]
27260 Cost:  0.9261346 
Prediction:
 [[151.31555]
 [185.70941]
 [180.96239]
 [194.483  ]
 [142.65686]]
27270 Cost:  0.92556226 
Prediction:
 [[151.31557]
 [185.70929]
 [180.96231]
 [194.48358]
 [142.65628]]
27280 Cost:  0.9249875 
Prediction:
 [[151.31558]
 [185.70915]
 [180.9622 ]
 [194.48415]
 [142.65572]]
27290 Cost:  0.92441046 
Prediction:
 [[151.3156 ]
 [185.70903]
 [180.96213]
 [194.48474]
 [142.65515]]
27300 Cost:  0.9238281 
Prediction:
 [[151.31563]
 [185.70892]
 [180.96204]
 [194.48534]
 [142.65459]]
27310 Cost:  0.92325515 
Prediction:
 [[151.31564]
 [185.7088 ]
 [180.96194]
 [194.48592]
 [142.65402]]
27320 Cost:  0.9226891 
Prediction:
 [[151.31567]
 [185.7087 ]
 [180.96188]
 [194.48651]
 [142.65347]]
27330 Cost:  0.9221071 
Prediction:
 [[151.3157 ]
 [185.70857]
 [180.9

28140 Cost:  0.8773753 
Prediction:
 [[151.31743]
 [185.69907]
 [180.95502]
 [194.53363]
 [142.60826]]
28150 Cost:  0.8768379 
Prediction:
 [[151.31744]
 [185.69894]
 [180.95494]
 [194.53421]
 [142.60773]]
28160 Cost:  0.8763151 
Prediction:
 [[151.31747]
 [185.69884]
 [180.95486]
 [194.53476]
 [142.60718]]
28170 Cost:  0.8757845 
Prediction:
 [[151.31749]
 [185.69872]
 [180.95476]
 [194.53531]
 [142.60664]]
28180 Cost:  0.8752581 
Prediction:
 [[151.31752]
 [185.69862]
 [180.9547 ]
 [194.53589]
 [142.60611]]
28190 Cost:  0.87472486 
Prediction:
 [[151.31754]
 [185.6985 ]
 [180.9546 ]
 [194.53645]
 [142.60558]]
28200 Cost:  0.8741845 
Prediction:
 [[151.31757]
 [185.69838]
 [180.95453]
 [194.53703]
 [142.60504]]
28210 Cost:  0.8736703 
Prediction:
 [[151.31758]
 [185.69827]
 [180.95444]
 [194.53757]
 [142.60449]]
28220 Cost:  0.8731348 
Prediction:
 [[151.3176 ]
 [185.69815]
 [180.95436]
 [194.53815]
 [142.60396]]
28230 Cost:  0.87261784 
Prediction:
 [[151.31761]
 [185.69804]
 [180.95

29100 Cost:  0.8286239 
Prediction:
 [[151.31947]
 [185.68826]
 [180.94736]
 [194.5865 ]
 [142.55753]]
29110 Cost:  0.8281352 
Prediction:
 [[151.31949]
 [185.68816]
 [180.94728]
 [194.58705]
 [142.557  ]]
29120 Cost:  0.82764685 
Prediction:
 [[151.3195 ]
 [185.68805]
 [180.9472 ]
 [194.5876 ]
 [142.55649]]
29130 Cost:  0.8271717 
Prediction:
 [[151.31953]
 [185.68794]
 [180.94713]
 [194.58812]
 [142.55597]]
29140 Cost:  0.82668245 
Prediction:
 [[151.31955]
 [185.68782]
 [180.94704]
 [194.58865]
 [142.55545]]
29150 Cost:  0.826194 
Prediction:
 [[151.31958]
 [185.68771]
 [180.94696]
 [194.5892 ]
 [142.55495]]
29160 Cost:  0.82572097 
Prediction:
 [[151.3196 ]
 [185.6876 ]
 [180.9469 ]
 [194.58974]
 [142.55443]]
29170 Cost:  0.82523984 
Prediction:
 [[151.31961]
 [185.6875 ]
 [180.94681]
 [194.59027]
 [142.55392]]
29180 Cost:  0.8247617 
Prediction:
 [[151.31964]
 [185.68738]
 [180.94673]
 [194.59079]
 [142.5534 ]]
29190 Cost:  0.8242658 
Prediction:
 [[151.31966]
 [185.68727]
 [180.9

30070 Cost:  0.78367615 
Prediction:
 [[151.32146]
 [185.67781]
 [180.93994]
 [194.63748]
 [142.50851]]
30080 Cost:  0.7832221 
Prediction:
 [[151.3215 ]
 [185.6777 ]
 [180.9399 ]
 [194.63803]
 [142.50804]]
30090 Cost:  0.7827962 
Prediction:
 [[151.3215 ]
 [185.6776 ]
 [180.93982]
 [194.63852]
 [142.50754]]
30100 Cost:  0.7823415 
Prediction:
 [[151.32152]
 [185.67749]
 [180.93974]
 [194.63905]
 [142.50703]]
30110 Cost:  0.7819041 
Prediction:
 [[151.32155]
 [185.6774 ]
 [180.93968]
 [194.63957]
 [142.50655]]
30120 Cost:  0.78145134 
Prediction:
 [[151.32158]
 [185.67729]
 [180.93959]
 [194.64009]
 [142.50606]]
30130 Cost:  0.7810185 
Prediction:
 [[151.32161]
 [185.67719]
 [180.93953]
 [194.6406 ]
 [142.50557]]
30140 Cost:  0.7805827 
Prediction:
 [[151.32161]
 [185.67708]
 [180.93944]
 [194.6411 ]
 [142.50508]]
30150 Cost:  0.7801457 
Prediction:
 [[151.32162]
 [185.67697]
 [180.93936]
 [194.6416 ]
 [142.50458]]
30160 Cost:  0.77969533 
Prediction:
 [[151.32166]
 [185.67685]
 [180.9

31010 Cost:  0.7438918 
Prediction:
 [[151.32336]
 [185.66814]
 [180.93314]
 [194.68471]
 [142.46312]]
31020 Cost:  0.743481 
Prediction:
 [[151.32338]
 [185.66803]
 [180.93306]
 [194.68521]
 [142.46266]]
31030 Cost:  0.7430715 
Prediction:
 [[151.32341]
 [185.66792]
 [180.93298]
 [194.6857 ]
 [142.46219]]
31040 Cost:  0.7426691 
Prediction:
 [[151.32343]
 [185.66782]
 [180.93292]
 [194.68619]
 [142.4617 ]]
31050 Cost:  0.7422726 
Prediction:
 [[151.32346]
 [185.66772]
 [180.93286]
 [194.68668]
 [142.46124]]
31060 Cost:  0.74185574 
Prediction:
 [[151.32347]
 [185.6676 ]
 [180.93279]
 [194.68718]
 [142.46077]]
31070 Cost:  0.7414632 
Prediction:
 [[151.32349]
 [185.66751]
 [180.93271]
 [194.68765]
 [142.4603 ]]
31080 Cost:  0.74105483 
Prediction:
 [[151.3235 ]
 [185.66742]
 [180.93263]
 [194.68816]
 [142.45982]]
31090 Cost:  0.740655 
Prediction:
 [[151.32353]
 [185.66731]
 [180.93257]
 [194.68864]
 [142.45937]]
31100 Cost:  0.7402522 
Prediction:
 [[151.32355]
 [185.66722]
 [180.9325

32010 Cost:  0.7052781 
Prediction:
 [[151.32532]
 [185.65826]
 [180.92622]
 [194.73268]
 [142.417  ]]
32020 Cost:  0.70490354 
Prediction:
 [[151.32535]
 [185.65817]
 [180.92613]
 [194.73314]
 [142.41655]]
32030 Cost:  0.7045373 
Prediction:
 [[151.32536]
 [185.65808]
 [180.92609]
 [194.73363]
 [142.4161 ]]
32040 Cost:  0.70416886 
Prediction:
 [[151.32538]
 [185.65797]
 [180.92601]
 [194.73409]
 [142.41565]]
32050 Cost:  0.70380497 
Prediction:
 [[151.3254 ]
 [185.65788]
 [180.92595]
 [194.73456]
 [142.4152 ]]
32060 Cost:  0.7034316 
Prediction:
 [[151.32542]
 [185.65779]
 [180.92587]
 [194.73503]
 [142.41476]]
32070 Cost:  0.70306766 
Prediction:
 [[151.32544]
 [185.6577 ]
 [180.9258 ]
 [194.73549]
 [142.4143 ]]
32080 Cost:  0.7027019 
Prediction:
 [[151.32544]
 [185.6576 ]
 [180.92574]
 [194.73596]
 [142.41385]]
32090 Cost:  0.7023383 
Prediction:
 [[151.32549]
 [185.6575 ]
 [180.92567]
 [194.73642]
 [142.4134 ]]
32100 Cost:  0.7019815 
Prediction:
 [[151.32549]
 [185.65741]
 [180.

33010 Cost:  0.6701518 
Prediction:
 [[151.3272 ]
 [185.64885]
 [180.9196 ]
 [194.77841]
 [142.37302]]
33020 Cost:  0.66982156 
Prediction:
 [[151.32721]
 [185.64876]
 [180.91954]
 [194.77885]
 [142.37259]]
33030 Cost:  0.6694839 
Prediction:
 [[151.32724]
 [185.64868]
 [180.91948]
 [194.77931]
 [142.37216]]
33040 Cost:  0.66916144 
Prediction:
 [[151.32726]
 [185.64859]
 [180.91942]
 [194.77974]
 [142.37173]]
33050 Cost:  0.668822 
Prediction:
 [[151.32727]
 [185.6485 ]
 [180.91936]
 [194.7802 ]
 [142.37129]]
33060 Cost:  0.6684885 
Prediction:
 [[151.32729]
 [185.64839]
 [180.9193 ]
 [194.78064]
 [142.37086]]
33070 Cost:  0.6681478 
Prediction:
 [[151.3273 ]
 [185.6483 ]
 [180.9192 ]
 [194.78108]
 [142.37044]]
33080 Cost:  0.6678182 
Prediction:
 [[151.32733]
 [185.64821]
 [180.91917]
 [194.78154]
 [142.37001]]
33090 Cost:  0.6674853 
Prediction:
 [[151.32735]
 [185.64812]
 [180.91908]
 [194.78197]
 [142.36958]]
33100 Cost:  0.6671659 
Prediction:
 [[151.32736]
 [185.64804]
 [180.919

33860 Cost:  0.6428181 
Prediction:
 [[151.32875]
 [185.6412 ]
 [180.91425]
 [194.8156 ]
 [142.33722]]
33870 Cost:  0.6425164 
Prediction:
 [[151.32875]
 [185.64111]
 [180.91418]
 [194.81602]
 [142.33682]]
33880 Cost:  0.64219743 
Prediction:
 [[151.32878]
 [185.64102]
 [180.91412]
 [194.81647]
 [142.33641]]
33890 Cost:  0.64189386 
Prediction:
 [[151.3288 ]
 [185.64095]
 [180.91406]
 [194.8169 ]
 [142.336  ]]
33900 Cost:  0.6415865 
Prediction:
 [[151.32881]
 [185.64085]
 [180.914  ]
 [194.81732]
 [142.33559]]
33910 Cost:  0.64128315 
Prediction:
 [[151.32883]
 [185.64078]
 [180.91394]
 [194.81775]
 [142.33517]]
33920 Cost:  0.6409681 
Prediction:
 [[151.32886]
 [185.64067]
 [180.91388]
 [194.81818]
 [142.33476]]
33930 Cost:  0.6406648 
Prediction:
 [[151.32886]
 [185.64058]
 [180.9138 ]
 [194.81859]
 [142.33434]]
33940 Cost:  0.64035594 
Prediction:
 [[151.32889]
 [185.64049]
 [180.91374]
 [194.81902]
 [142.33394]]
33950 Cost:  0.64004725 
Prediction:
 [[151.3289 ]
 [185.6404 ]
 [180

34860 Cost:  0.61335814 
Prediction:
 [[151.33047]
 [185.63257]
 [180.9082 ]
 [194.85747]
 [142.29694]]
34870 Cost:  0.61307317 
Prediction:
 [[151.3305 ]
 [185.63249]
 [180.90814]
 [194.85788]
 [142.29654]]
34880 Cost:  0.61279935 
Prediction:
 [[151.33052]
 [185.63242]
 [180.90808]
 [194.85828]
 [142.29614]]
34890 Cost:  0.6125079 
Prediction:
 [[151.33054]
 [185.63232]
 [180.90802]
 [194.8587 ]
 [142.29575]]
34900 Cost:  0.6122323 
Prediction:
 [[151.33055]
 [185.63223]
 [180.90796]
 [194.8591 ]
 [142.29536]]
34910 Cost:  0.6119538 
Prediction:
 [[151.33057]
 [185.63216]
 [180.9079 ]
 [194.85951]
 [142.29498]]
34920 Cost:  0.6116752 
Prediction:
 [[151.33058]
 [185.63206]
 [180.90785]
 [194.85992]
 [142.29459]]
34930 Cost:  0.6113924 
Prediction:
 [[151.33061]
 [185.63197]
 [180.90779]
 [194.86032]
 [142.29417]]
34940 Cost:  0.6111164 
Prediction:
 [[151.33061]
 [185.6319 ]
 [180.90773]
 [194.86073]
 [142.29378]]
34950 Cost:  0.6108454 
Prediction:
 [[151.33063]
 [185.63182]
 [180.9

35860 Cost:  0.58654207 
Prediction:
 [[151.33217]
 [185.62431]
 [180.90242]
 [194.89738]
 [142.2585 ]]
35870 Cost:  0.5862975 
Prediction:
 [[151.33217]
 [185.62425]
 [180.90237]
 [194.89778]
 [142.25813]]
35880 Cost:  0.5860441 
Prediction:
 [[151.3322 ]
 [185.62416]
 [180.90233]
 [194.89816]
 [142.25777]]
35890 Cost:  0.5857953 
Prediction:
 [[151.33221]
 [185.6241 ]
 [180.90227]
 [194.89854]
 [142.25739]]
35900 Cost:  0.58552986 
Prediction:
 [[151.33224]
 [185.62401]
 [180.9022 ]
 [194.89894]
 [142.25702]]
35910 Cost:  0.5852696 
Prediction:
 [[151.33226]
 [185.62393]
 [180.90216]
 [194.89935]
 [142.25664]]
35920 Cost:  0.58502686 
Prediction:
 [[151.33226]
 [185.62387]
 [180.9021 ]
 [194.89973]
 [142.25627]]
35930 Cost:  0.5847765 
Prediction:
 [[151.33228]
 [185.62378]
 [180.90205]
 [194.90012]
 [142.25589]]
35940 Cost:  0.5845153 
Prediction:
 [[151.3323 ]
 [185.6237 ]
 [180.902  ]
 [194.90051]
 [142.25552]]
35950 Cost:  0.58426756 
Prediction:
 [[151.3323 ]
 [185.62363]
 [180.

36790 Cost:  0.5638021 
Prediction:
 [[151.33366]
 [185.61702]
 [180.89731]
 [194.93286]
 [142.22438]]
36800 Cost:  0.5635751 
Prediction:
 [[151.33368]
 [185.61694]
 [180.89726]
 [194.93323]
 [142.22403]]
36810 Cost:  0.5633429 
Prediction:
 [[151.3337 ]
 [185.61685]
 [180.89722]
 [194.9336 ]
 [142.22366]]
36820 Cost:  0.5631 
Prediction:
 [[151.33371]
 [185.61679]
 [180.89716]
 [194.93399]
 [142.2233 ]]
36830 Cost:  0.562864 
Prediction:
 [[151.33372]
 [185.6167 ]
 [180.8971 ]
 [194.93436]
 [142.22295]]
36840 Cost:  0.5626435 
Prediction:
 [[151.33374]
 [185.61662]
 [180.89703]
 [194.9347 ]
 [142.22258]]
36850 Cost:  0.5624105 
Prediction:
 [[151.33376]
 [185.61655]
 [180.89699]
 [194.93507]
 [142.22223]]
36860 Cost:  0.5621799 
Prediction:
 [[151.33377]
 [185.61649]
 [180.89694]
 [194.93546]
 [142.22186]]
36870 Cost:  0.56194985 
Prediction:
 [[151.33379]
 [185.6164 ]
 [180.8969 ]
 [194.93582]
 [142.22151]]
36880 Cost:  0.5617113 
Prediction:
 [[151.33382]
 [185.61633]
 [180.89684]


37810 Cost:  0.5410552 
Prediction:
 [[151.33524]
 [185.60934]
 [180.89195]
 [194.97   ]
 [142.18864]]
37820 Cost:  0.54084486 
Prediction:
 [[151.33527]
 [185.60928]
 [180.8919 ]
 [194.97035]
 [142.1883 ]]
37830 Cost:  0.54063094 
Prediction:
 [[151.33527]
 [185.60919]
 [180.89185]
 [194.9707 ]
 [142.18796]]
37840 Cost:  0.54042745 
Prediction:
 [[151.3353 ]
 [185.60913]
 [180.89182]
 [194.97105]
 [142.18762]]
37850 Cost:  0.54021084 
Prediction:
 [[151.3353 ]
 [185.60905]
 [180.89174]
 [194.9714 ]
 [142.18727]]
37860 Cost:  0.53999496 
Prediction:
 [[151.33531]
 [185.60898]
 [180.8917 ]
 [194.97177]
 [142.18692]]
37870 Cost:  0.5397912 
Prediction:
 [[151.33533]
 [185.60892]
 [180.89163]
 [194.9721 ]
 [142.18658]]
37880 Cost:  0.5395784 
Prediction:
 [[151.33534]
 [185.60883]
 [180.8916 ]
 [194.97247]
 [142.18625]]
37890 Cost:  0.5393676 
Prediction:
 [[151.33536]
 [185.60876]
 [180.89156]
 [194.97284]
 [142.18591]]
37900 Cost:  0.53916585 
Prediction:
 [[151.33537]
 [185.60869]
 [18

38790 Cost:  0.52117944 
Prediction:
 [[151.33669]
 [185.60231]
 [180.88704]
 [195.00401]
 [142.1559 ]]
38800 Cost:  0.5209803 
Prediction:
 [[151.33672]
 [185.60225]
 [180.88698]
 [195.00435]
 [142.15556]]
38810 Cost:  0.5207914 
Prediction:
 [[151.33672]
 [185.60217]
 [180.88695]
 [195.0047 ]
 [142.15524]]
38820 Cost:  0.520599 
Prediction:
 [[151.33673]
 [185.6021 ]
 [180.88689]
 [195.00502]
 [142.1549 ]]
38830 Cost:  0.52040994 
Prediction:
 [[151.33675]
 [185.60204]
 [180.88686]
 [195.00537]
 [142.15459]]
38840 Cost:  0.52021617 
Prediction:
 [[151.33676]
 [185.60197]
 [180.8868 ]
 [195.0057 ]
 [142.15427]]
38850 Cost:  0.5200237 
Prediction:
 [[151.33678]
 [185.6019 ]
 [180.88676]
 [195.00606]
 [142.15395]]
38860 Cost:  0.5198215 
Prediction:
 [[151.3368 ]
 [185.60182]
 [180.8867 ]
 [195.0064 ]
 [142.15361]]
38870 Cost:  0.5196334 
Prediction:
 [[151.33682]
 [185.60176]
 [180.88666]
 [195.00673]
 [142.15329]]
38880 Cost:  0.5194455 
Prediction:
 [[151.33684]
 [185.6017 ]
 [180.88

39720 Cost:  0.5039446 
Prediction:
 [[151.33801]
 [185.59593]
 [180.88258]
 [195.03487]
 [142.12619]]
39730 Cost:  0.5037641 
Prediction:
 [[151.33803]
 [185.59587]
 [180.88254]
 [195.0352 ]
 [142.12587]]
39740 Cost:  0.50359035 
Prediction:
 [[151.33804]
 [185.59581]
 [180.88249]
 [195.03552]
 [142.12556]]
39750 Cost:  0.5034167 
Prediction:
 [[151.33806]
 [185.59575]
 [180.88245]
 [195.03584]
 [142.12526]]
39760 Cost:  0.5032336 
Prediction:
 [[151.33807]
 [185.59567]
 [180.8824 ]
 [195.03618]
 [142.12495]]
39770 Cost:  0.50306165 
Prediction:
 [[151.33809]
 [185.5956 ]
 [180.88235]
 [195.03648]
 [142.12463]]
39780 Cost:  0.50288236 
Prediction:
 [[151.3381 ]
 [185.59554]
 [180.88231]
 [195.03682]
 [142.12433]]
39790 Cost:  0.50270873 
Prediction:
 [[151.33812]
 [185.59547]
 [180.88225]
 [195.03712]
 [142.12401]]
39800 Cost:  0.5025314 
Prediction:
 [[151.33813]
 [185.5954 ]
 [180.88222]
 [195.03746]
 [142.1237 ]]
39810 Cost:  0.5023582 
Prediction:
 [[151.33815]
 [185.59534]
 [180.